{
 "title": "Attic - Users",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Alloc ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_info" }
   ]
  },
  {
   "title": "Create User Request - Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "users_service_create_request_count"
    }
   ]
  },
  {
   "title": "GO - INFO",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_info" }
   ]
  },
  {
   "title": "Create User - Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "users_service_create_request_latency_microseconds_count{method=\"create\",type=\"requestsLatency\"}"
    }
   ]
  },
  {
   "title": "GC - Duration",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_gc_duration_seconds" }
   ]
  },
  {
   "title": "Gorotines - Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "go_goroutines" }
   ]
  }
 ]
}