// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/physical_environment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhysicalEnvironmentRequestEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PhysicalEnvironmentRequestEmpty) Reset() {
	*x = PhysicalEnvironmentRequestEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_physical_environment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhysicalEnvironmentRequestEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalEnvironmentRequestEmpty) ProtoMessage() {}

func (x *PhysicalEnvironmentRequestEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_physical_environment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalEnvironmentRequestEmpty.ProtoReflect.Descriptor instead.
func (*PhysicalEnvironmentRequestEmpty) Descriptor() ([]byte, []int) {
	return file_proto_physical_environment_proto_rawDescGZIP(), []int{0}
}

type PhysicalEnvironmentGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *PhysicalEnvironmentGetRequest) Reset() {
	*x = PhysicalEnvironmentGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_physical_environment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhysicalEnvironmentGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalEnvironmentGetRequest) ProtoMessage() {}

func (x *PhysicalEnvironmentGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_physical_environment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalEnvironmentGetRequest.ProtoReflect.Descriptor instead.
func (*PhysicalEnvironmentGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_physical_environment_proto_rawDescGZIP(), []int{1}
}

func (x *PhysicalEnvironmentGetRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type PhysicalEnvironmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Active bool   `protobuf:"varint,3,opt,name=Active,proto3" json:"Active,omitempty"`
	UserID int64  `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *PhysicalEnvironmentRequest) Reset() {
	*x = PhysicalEnvironmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_physical_environment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhysicalEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalEnvironmentRequest) ProtoMessage() {}

func (x *PhysicalEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_physical_environment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*PhysicalEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_physical_environment_proto_rawDescGZIP(), []int{2}
}

func (x *PhysicalEnvironmentRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *PhysicalEnvironmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhysicalEnvironmentRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *PhysicalEnvironmentRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type PhysicalEnvironmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Active bool   `protobuf:"varint,3,opt,name=Active,proto3" json:"Active,omitempty"`
	UserID int64  `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *PhysicalEnvironmentResponse) Reset() {
	*x = PhysicalEnvironmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_physical_environment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhysicalEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalEnvironmentResponse) ProtoMessage() {}

func (x *PhysicalEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_physical_environment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*PhysicalEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_physical_environment_proto_rawDescGZIP(), []int{3}
}

func (x *PhysicalEnvironmentResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *PhysicalEnvironmentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhysicalEnvironmentResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *PhysicalEnvironmentResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type PhysicalEnvironmentResponseList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhysicalEnvironment []*PhysicalEnvironmentResponse `protobuf:"bytes,1,rep,name=PhysicalEnvironment,proto3" json:"PhysicalEnvironment,omitempty"`
}

func (x *PhysicalEnvironmentResponseList) Reset() {
	*x = PhysicalEnvironmentResponseList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_physical_environment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhysicalEnvironmentResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalEnvironmentResponseList) ProtoMessage() {}

func (x *PhysicalEnvironmentResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_physical_environment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalEnvironmentResponseList.ProtoReflect.Descriptor instead.
func (*PhysicalEnvironmentResponseList) Descriptor() ([]byte, []int) {
	return file_proto_physical_environment_proto_rawDescGZIP(), []int{4}
}

func (x *PhysicalEnvironmentResponseList) GetPhysicalEnvironment() []*PhysicalEnvironmentResponse {
	if x != nil {
		return x.PhysicalEnvironment
	}
	return nil
}

var File_proto_physical_environment_proto protoreflect.FileDescriptor

var file_proto_physical_environment_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c,
	0x5f, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x21, 0x0a, 0x1f, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63,
	0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2f, 0x0a, 0x1d, 0x50, 0x68, 0x79,
	0x73, 0x69, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x70, 0x0a, 0x1a, 0x50, 0x68,
	0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x71, 0x0a, 0x1b,
	0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22,
	0x74, 0x0a, 0x1f, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x51, 0x0a, 0x13, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x45, 0x6e,
	0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x13, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0xd0, 0x02, 0x0a, 0x13, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63,
	0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x4b, 0x0a,
	0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x68, 0x79,
	0x73, 0x69, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x68, 0x79,
	0x73, 0x69, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63,
	0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63,
	0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x21,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x45,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x45,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_physical_environment_proto_rawDescOnce sync.Once
	file_proto_physical_environment_proto_rawDescData = file_proto_physical_environment_proto_rawDesc
)

func file_proto_physical_environment_proto_rawDescGZIP() []byte {
	file_proto_physical_environment_proto_rawDescOnce.Do(func() {
		file_proto_physical_environment_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_physical_environment_proto_rawDescData)
	})
	return file_proto_physical_environment_proto_rawDescData
}

var file_proto_physical_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_physical_environment_proto_goTypes = []interface{}{
	(*PhysicalEnvironmentRequestEmpty)(nil), // 0: pb.PhysicalEnvironmentRequestEmpty
	(*PhysicalEnvironmentGetRequest)(nil),   // 1: pb.PhysicalEnvironmentGetRequest
	(*PhysicalEnvironmentRequest)(nil),      // 2: pb.PhysicalEnvironmentRequest
	(*PhysicalEnvironmentResponse)(nil),     // 3: pb.PhysicalEnvironmentResponse
	(*PhysicalEnvironmentResponseList)(nil), // 4: pb.PhysicalEnvironmentResponseList
}
var file_proto_physical_environment_proto_depIdxs = []int32{
	3, // 0: pb.PhysicalEnvironmentResponseList.PhysicalEnvironment:type_name -> pb.PhysicalEnvironmentResponse
	2, // 1: pb.PhysicalEnvironment.Create:input_type -> pb.PhysicalEnvironmentRequest
	2, // 2: pb.PhysicalEnvironment.Update:input_type -> pb.PhysicalEnvironmentRequest
	1, // 3: pb.PhysicalEnvironment.Get:input_type -> pb.PhysicalEnvironmentGetRequest
	0, // 4: pb.PhysicalEnvironment.List:input_type -> pb.PhysicalEnvironmentRequestEmpty
	3, // 5: pb.PhysicalEnvironment.Create:output_type -> pb.PhysicalEnvironmentResponse
	3, // 6: pb.PhysicalEnvironment.Update:output_type -> pb.PhysicalEnvironmentResponse
	3, // 7: pb.PhysicalEnvironment.Get:output_type -> pb.PhysicalEnvironmentResponse
	4, // 8: pb.PhysicalEnvironment.List:output_type -> pb.PhysicalEnvironmentResponseList
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_physical_environment_proto_init() }
func file_proto_physical_environment_proto_init() {
	if File_proto_physical_environment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_physical_environment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhysicalEnvironmentRequestEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_physical_environment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhysicalEnvironmentGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_physical_environment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhysicalEnvironmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_physical_environment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhysicalEnvironmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_physical_environment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhysicalEnvironmentResponseList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_physical_environment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_physical_environment_proto_goTypes,
		DependencyIndexes: file_proto_physical_environment_proto_depIdxs,
		MessageInfos:      file_proto_physical_environment_proto_msgTypes,
	}.Build()
	File_proto_physical_environment_proto = out.File
	file_proto_physical_environment_proto_rawDesc = nil
	file_proto_physical_environment_proto_goTypes = nil
	file_proto_physical_environment_proto_depIdxs = nil
}
